spring:
  redis:
    #redis机器ip
    host: localhost
    #redis端口
    port: 6379
    #redis密码
    #password: 123456
    #redis 连接超时时间（毫秒），如果不设置，取默认值2000
    timeout: 10000
    lettuce:
      pool:
        max-idle: 100 #最大空闲数
        #连接池的最大数据库连接数。设为0表示无限制,如果是jedis 2.4以后用redis.maxTotal
#        max-active: 100
    #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
#    maxWaitMillis: 1000
    #连接的最小空闲时间 默认1800000毫秒(30分钟)
#    minEvictableIdleTimeMillis: 300000
    #每次释放连接的最大数目,默认3
#    numTestsPerEvictionRun: 1024
    #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
#    timeBetweenEvictionRunsMillis: 30000
    #是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
#    testOnBorrow: true
    #在空闲时检查有效性, 默认false
#    testWhileIdle: true
#redis的core包下的日志输出
#logging:
#  level:
#    org.springframework.data.redis.core : debug
